// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: messenger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType describes the plaintext kind so the recipient can render it.
// The server never sees plaintext; this only travels inside encrypted payloads
// in practice, but type is kept on the envelope for routing/feed previews that
// are themselves derived client-side.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_IMAGE       MessageType = 2
	MessageType_MESSAGE_TYPE_FILE        MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_FILE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_IMAGE":       2,
		"MESSAGE_TYPE_FILE":        3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messenger_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messenger_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{0}
}

type Receipt_Kind int32

const (
	Receipt_KIND_UNSPECIFIED Receipt_Kind = 0
	Receipt_KIND_DELIVERED   Receipt_Kind = 1
	Receipt_KIND_READ        Receipt_Kind = 2
)

// Enum value maps for Receipt_Kind.
var (
	Receipt_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_DELIVERED",
		2: "KIND_READ",
	}
	Receipt_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_DELIVERED":   1,
		"KIND_READ":        2,
	}
)

func (x Receipt_Kind) Enum() *Receipt_Kind {
	p := new(Receipt_Kind)
	*p = x
	return p
}

func (x Receipt_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Receipt_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_messenger_proto_enumTypes[1].Descriptor()
}

func (Receipt_Kind) Type() protoreflect.EnumType {
	return &file_messenger_proto_enumTypes[1]
}

func (x Receipt_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Receipt_Kind.Descriptor instead.
func (Receipt_Kind) EnumDescriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{4, 0}
}

// Envelope is the single frame type sent over the websocket in both directions.
// Exactly one payload is set via the oneof.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated id used to correlate Ack responses. Optional for
	// server-originated frames.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Send
	//	*Envelope_Incoming
	//	*Envelope_Ack
	//	*Envelope_Receipt
	//	*Envelope_Presence
	//	*Envelope_Typing
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSend() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *Envelope) GetIncoming() *IncomingMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Incoming); ok {
			return x.Incoming
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetReceipt() *Receipt {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *Envelope) GetPresence() *Presence {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *Envelope) GetTyping() *Typing {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Send struct {
	Send *SendMessage `protobuf:"bytes,10,opt,name=send,proto3,oneof"`
}

type Envelope_Incoming struct {
	Incoming *IncomingMessage `protobuf:"bytes,11,opt,name=incoming,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,12,opt,name=ack,proto3,oneof"`
}

type Envelope_Receipt struct {
	Receipt *Receipt `protobuf:"bytes,13,opt,name=receipt,proto3,oneof"`
}

type Envelope_Presence struct {
	Presence *Presence `protobuf:"bytes,14,opt,name=presence,proto3,oneof"`
}

type Envelope_Typing struct {
	Typing *Typing `protobuf:"bytes,15,opt,name=typing,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,16,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,17,opt,name=pong,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,18,opt,name=error,proto3,oneof"`
}

func (*Envelope_Send) isEnvelope_Payload() {}

func (*Envelope_Incoming) isEnvelope_Payload() {}

func (*Envelope_Ack) isEnvelope_Payload() {}

func (*Envelope_Receipt) isEnvelope_Payload() {}

func (*Envelope_Presence) isEnvelope_Payload() {}

func (*Envelope_Typing) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

// SendMessage is client -> server: deliver this ciphertext to recipient.
type SendMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RecipientId string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	// Opaque Double Ratchet ciphertext (the server cannot read it).
	Ciphertext []byte      `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Type       MessageType `protobuf:"varint,3,opt,name=type,proto3,enum=messenger.v1.MessageType" json:"type,omitempty"`
	// True when this is the first message of a new session and carries the
	// X3DH prekey handshake header (recipient needs it to bootstrap the session).
	IsPrekey      bool `protobuf:"varint,4,opt,name=is_prekey,json=isPrekey,proto3" json:"is_prekey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SendMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SendMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *SendMessage) GetIsPrekey() bool {
	if x != nil {
		return x.IsPrekey
	}
	return false
}

// IncomingMessage is server -> client: a message addressed to the receiver.
type IncomingMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Ciphertext      []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Type            MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=messenger.v1.MessageType" json:"type,omitempty"`
	IsPrekey        bool                   `protobuf:"varint,5,opt,name=is_prekey,json=isPrekey,proto3" json:"is_prekey,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IncomingMessage) Reset() {
	*x = IncomingMessage{}
	mi := &file_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessage) ProtoMessage() {}

func (x *IncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessage.ProtoReflect.Descriptor instead.
func (*IncomingMessage) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *IncomingMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *IncomingMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *IncomingMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *IncomingMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *IncomingMessage) GetIsPrekey() bool {
	if x != nil {
		return x.IsPrekey
	}
	return false
}

func (x *IncomingMessage) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

// Ack is server -> client confirming receipt/persistence of a SendMessage,
// echoing the client envelope id and assigning a server message id.
type Ack struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,3,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Ack) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

// Receipt is client -> server (then relayed to the original sender) indicating
// the message was delivered to / read by the recipient device.
type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // original sender to notify
	Kind          Receipt_Kind           `protobuf:"varint,3,opt,name=kind,proto3,enum=messenger.v1.Receipt_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{4}
}

func (x *Receipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Receipt) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Receipt) GetKind() Receipt_Kind {
	if x != nil {
		return x.Kind
	}
	return Receipt_KIND_UNSPECIFIED
}

type Presence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Online         bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	LastSeenUnixMs int64                  `protobuf:"varint,3,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_messenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{5}
}

func (x *Presence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Presence) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Presence) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type Typing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // sender when c->s target; sender id when s->c
	Typing        bool                   `protobuf:"varint,2,opt,name=typing,proto3" json:"typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Typing) Reset() {
	*x = Typing{}
	mi := &file_messenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Typing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typing) ProtoMessage() {}

func (x *Typing) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Typing.ProtoReflect.Descriptor instead.
func (*Typing) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{6}
}

func (x *Typing) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Typing) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_messenger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{7}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_messenger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{8}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_messenger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_messenger_proto protoreflect.FileDescriptor

const file_messenger_proto_rawDesc = "" +
	"\n" +
	"\x0fmessenger.proto\x12\fmessenger.v1\"\xd4\x03\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04send\x18\n" +
	" \x01(\v2\x19.messenger.v1.SendMessageH\x00R\x04send\x12;\n" +
	"\bincoming\x18\v \x01(\v2\x1d.messenger.v1.IncomingMessageH\x00R\bincoming\x12%\n" +
	"\x03ack\x18\f \x01(\v2\x11.messenger.v1.AckH\x00R\x03ack\x121\n" +
	"\areceipt\x18\r \x01(\v2\x15.messenger.v1.ReceiptH\x00R\areceipt\x124\n" +
	"\bpresence\x18\x0e \x01(\v2\x16.messenger.v1.PresenceH\x00R\bpresence\x12.\n" +
	"\x06typing\x18\x0f \x01(\v2\x14.messenger.v1.TypingH\x00R\x06typing\x12(\n" +
	"\x04ping\x18\x10 \x01(\v2\x12.messenger.v1.PingH\x00R\x04ping\x12(\n" +
	"\x04pong\x18\x11 \x01(\v2\x12.messenger.v1.PongH\x00R\x04pong\x12+\n" +
	"\x05error\x18\x12 \x01(\v2\x13.messenger.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x9c\x01\n" +
	"\vSendMessage\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.messenger.v1.MessageTypeR\x04type\x12\x1b\n" +
	"\tis_prekey\x18\x04 \x01(\bR\bisPrekey\"\xe6\x01\n" +
	"\x0fIncomingMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.messenger.v1.MessageTypeR\x04type\x12\x1b\n" +
	"\tis_prekey\x18\x05 \x01(\bR\bisPrekey\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMs\"n\n" +
	"\x03Ack\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12+\n" +
	"\x12created_at_unix_ms\x18\x03 \x01(\x03R\x0fcreatedAtUnixMs\"\xb6\x01\n" +
	"\aReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12.\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1a.messenger.v1.Receipt.KindR\x04kind\"?\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKIND_DELIVERED\x10\x01\x12\r\n" +
	"\tKIND_READ\x10\x02\"f\n" +
	"\bPresence\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12)\n" +
	"\x11last_seen_unix_ms\x18\x03 \x01(\x03R\x0elastSeenUnixMs\"9\n" +
	"\x06Typing\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06typing\x18\x02 \x01(\bR\x06typing\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*q\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x03B.Z,github.com/whiterabbit/server/internal/pb;pbb\x06proto3"

var (
	file_messenger_proto_rawDescOnce sync.Once
	file_messenger_proto_rawDescData []byte
)

func file_messenger_proto_rawDescGZIP() []byte {
	file_messenger_proto_rawDescOnce.Do(func() {
		file_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)))
	})
	return file_messenger_proto_rawDescData
}

var file_messenger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_messenger_proto_goTypes = []any{
	(MessageType)(0),        // 0: messenger.v1.MessageType
	(Receipt_Kind)(0),       // 1: messenger.v1.Receipt.Kind
	(*Envelope)(nil),        // 2: messenger.v1.Envelope
	(*SendMessage)(nil),     // 3: messenger.v1.SendMessage
	(*IncomingMessage)(nil), // 4: messenger.v1.IncomingMessage
	(*Ack)(nil),             // 5: messenger.v1.Ack
	(*Receipt)(nil),         // 6: messenger.v1.Receipt
	(*Presence)(nil),        // 7: messenger.v1.Presence
	(*Typing)(nil),          // 8: messenger.v1.Typing
	(*Ping)(nil),            // 9: messenger.v1.Ping
	(*Pong)(nil),            // 10: messenger.v1.Pong
	(*Error)(nil),           // 11: messenger.v1.Error
}
var file_messenger_proto_depIdxs = []int32{
	3,  // 0: messenger.v1.Envelope.send:type_name -> messenger.v1.SendMessage
	4,  // 1: messenger.v1.Envelope.incoming:type_name -> messenger.v1.IncomingMessage
	5,  // 2: messenger.v1.Envelope.ack:type_name -> messenger.v1.Ack
	6,  // 3: messenger.v1.Envelope.receipt:type_name -> messenger.v1.Receipt
	7,  // 4: messenger.v1.Envelope.presence:type_name -> messenger.v1.Presence
	8,  // 5: messenger.v1.Envelope.typing:type_name -> messenger.v1.Typing
	9,  // 6: messenger.v1.Envelope.ping:type_name -> messenger.v1.Ping
	10, // 7: messenger.v1.Envelope.pong:type_name -> messenger.v1.Pong
	11, // 8: messenger.v1.Envelope.error:type_name -> messenger.v1.Error
	0,  // 9: messenger.v1.SendMessage.type:type_name -> messenger.v1.MessageType
	0,  // 10: messenger.v1.IncomingMessage.type:type_name -> messenger.v1.MessageType
	1,  // 11: messenger.v1.Receipt.kind:type_name -> messenger.v1.Receipt.Kind
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_messenger_proto_init() }
func file_messenger_proto_init() {
	if File_messenger_proto != nil {
		return
	}
	file_messenger_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Send)(nil),
		(*Envelope_Incoming)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_Receipt)(nil),
		(*Envelope_Presence)(nil),
		(*Envelope_Typing)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messenger_proto_goTypes,
		DependencyIndexes: file_messenger_proto_depIdxs,
		EnumInfos:         file_messenger_proto_enumTypes,
		MessageInfos:      file_messenger_proto_msgTypes,
	}.Build()
	File_messenger_proto = out.File
	file_messenger_proto_goTypes = nil
	file_messenger_proto_depIdxs = nil
}
